# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Instagram.Image')),
            ],
        ),
    ]
