# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
